### PR TITLE
fix: 🐛 found statements work also with floats 

### LINKED ISSUE #754: verify is found in
Zencode: 

```
Given that I have a 'string dictionary' named 'Information'

If I verify 'myNumber' is found in 'Information' 
then print string 'found'
endif

Then print data 
```

Data: 

```
{
	"Information": {
		"Metadata": "TransactionsBatchB6789",
		"Buyer": "John Doe",
		"myNumber": 3
	}
}

```

Error: 

1698837621603W[W] Given that I have a 'string dictionary' named 'Information'
1698837621603W[W] D ZEN:pick found Information(d)
1698837621603W[W] If I verify 'myNumber' is found in 'Information'
1698837621603W[W] [!] /zencode_when.lua:40: attempt to get length of a zenroom.float value (field '?')
1698837621603E[!] ERROR:
1698837621603E[!] EXEC: /zencode.lua:803: If I verify 'myNumber' is found in 'Information'
1698837621603E[!] Execution aborted
1698837621603E[!] Execution aborted with errors.

### PR DESCRIPTION
**Pull request by matteo-cristino**
fix #754

### CODE REVIEW

File: src/lua/zencode_when.lua [hunk 1]
```diff
@@ -27,7 +27,7 @@ When("done", function() end)
 
 
 local function _is_found(el)
-    return ACK[el] and (luatype(ACK[el]) == 'table' or #ACK[el] ~= 0)
+    return ACK[el] and (luatype(ACK[el]) == 'table' or tonumber(ACK[el]) or #ACK[el] ~= 0)
```
Comment (jaromil) [inline src/lua/zencode_when.lua:30]: we have the safer `table_size()` in place of the `#` overload which may be convenient to use here.

Comment (matteo-cristino) [reply src/lua/zencode_when.lua:30]: The # is used to check that `ACK[el]` is not an empty string. Empty table are accepted since it return true at the first check and thus the others checks are not performed. Do we want to modify it and return as not found also empty tables?

**Comment by jaromil** [comment]
xcellent!
